version: '3.8'

# This is a base docker-compose file with common configurations
# Use docker-compose.dev.yml or docker-compose.prod.yml for environment-specific settings

services:
  # Base service configurations (shared between environments)
  legalcontext:
    build:
      context: .
    environment:
      - PORT=3000
      
volumes:
  node_modules:
